package fluidlearn;

public enum Permessi {
    VISUALIZZARE_CONTRIBUTI_CLASSE,
    VISUALIZZARE_CONTRIBUTI_DOCENTE,
    CREARE_POST,
    CANCELLARE_POST,
    COMMENTARE,
    CREARE_COMPITI,
    CONSEGNARE_COMPITI,
    VALUTARE_COMPITI
}
